### ISSUE TITLE
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples' parameter of DBSCAN must be an int in the range [1, inf). Got 1.619289340101523 instead.

### ISSUE THREAD

**Issue by joy99xhs** [liyihao17/KANN-DBSCAN#1]
/Users/wangjieyi/PythonProjects/pythonProject/.venv/bin/python /Users/wangjieyi/PythonProjects/pythonProject/KANN-DBASCAN.py 
Traceback (most recent call last):
  File "/Users/wangjieyi/PythonProjects/pythonProject/KANN-DBASCAN.py", line 128, in <module>
    ClusterNumberList = returnClusterNumberList(dataSet,EpsCandidate,MinptsCandidate)
  File "/Users/wangjieyi/PythonProjects/pythonProject/KANN-DBASCAN.py", line 118, in returnClusterNumberList
    clustering = DBSCAN(eps= EpsCandidate[i],min_samples= MinptsCandidate[i]).fit(np_dataset)
  File "/Users/wangjieyi/PythonProjects/pythonProject/.venv/lib/python3.9/site-packages/sklearn/base.py", line 1467, in wrapper
    estimator._validate_params()
  File "/Users/wangjieyi/PythonProjects/pythonProject/.venv/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/Users/wangjieyi/PythonProjects/pythonProject/.venv/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples' parameter of DBSCAN must be an int in the range [1, inf). Got 1.619289340101523 instead.

**Comment by haomw01** [comment]
请问怎么解决的呢
